[[integrations]]
= Standards and integrations

[[other-integrations-jakarta]]
== Jakarta EE

When standard APIs are involved,
Hibernate Search targets link:{jakartaUrl}[Jakarta EE] by default.

[[other-integrations-javaee]]
== Java EE

Hibernate Search includes legacy support for link:{javaeeUrl}[Java EE],
and it requires only one small change:
when declaring the dependencies of your project,
you must add `-javaee` to some artifact identifiers.

For example, an application using Hibernate ORM and the Elasticsearch backend
will need to update its dependencies as follows:

[source, XML, subs="+attributes"]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-core-javaee</artifactId> <!--1-->
   <version>{hibernateVersion}</version>
</dependency>
<dependency>
   <groupId>org.hibernate.search</groupId>
   <artifactId>hibernate-search-mapper-orm-javaee</artifactId> <!--2-->
   <version>{hibernateSearchVersion}</version>
</dependency>
<dependency>
   <groupId>org.hibernate.search</groupId>
   <artifactId>hibernate-search-backend-elasticsearch</artifactId> <!--3-->
   <version>{hibernateSearchVersion}</version>
</dependency>
----
<1> Replaces `hibernate-core`.
<2> Replaces `hibernate-search-mapper-orm`.
<3> No replacement necessary: this artifact does not rely on Jakarta EE.

All artifacts relying directly or indirectly on Jakarta EE must be replaced with their Java EE counterpart.
This includes in particular:

* https://in.relation.to/2021/06/04/hibernate-is-jakarta-jpa-2/#get-it[Hibernate ORM artifacts]
* `hibernate-search-mapper-orm` => `hibernate-search-mapper-orm-javaee`
* `hibernate-search-mapper-orm-batch-jsr352-core` => `hibernate-search-mapper-orm-batch-jsr352-core-javaee`
* ...

Artifacts that do not rely on Jakarta EE at all, on the other hand,
do not have a Java EE counterpart and must not be replaced.
These artifacts should be excluded from your replacements in particular:

* `hibernate-search-engine`
* `hibernate-search-backend-lucene`
* `hibernate-search-backend-elasticsearch`
* `hibernate-search-backend-elasticsearch-aws`
* ...
